keys:
  - &earthnuker age1hf0avdess0rgg4t9ulr2zvuanu4l24a5ns2p25pwqrhj7c50ga4s5w5rk5
  - &godwaker age189fxupplvl3hm20guvedtmk4utekly9kp7zug5em6jf4yl2anu0q224zwh
  - &talos age1mpk8wz3u752pdy45vd2lq6tnk6r949mh9sswzyk6ka32d0qlx9ssnpxr29
creation_rules:
  - path_regex: .*
    key_groups:
      - age:
          - *earthnuker
          - *godwaker
          - *talos
