keys:
  - &earthnuker age1hf0avdess0rgg4t9ulr2zvuanu4l24a5ns2p25pwqrhj7c50ga4s5w5rk5
  - &godwaker age144g8xpr2zgp5h4gt2u2pl3dh4h52vtna2fnpzsmsrcwjsjhnq4kq48us6k
  - &talos age14qr4ej0j8rtyxy0py566deyj3cd4h7tarrnc927v07znz2e6eevqerg0hp
creation_rules:
  - path_regex: secrets.yml$
    key_groups:
      - age:
          - *earthnuker
          - *godwaker
          - *talos
